### ISSUE TITLE
react-router 사용해서 화면을 이동해주세요.

### ISSUE THREAD

**Issue by Yeri-Kim** [ahndohyun/miniter_project#1]
https://yeri-kim.github.io/posts/react-router/
참고하세요

회원가입, 로그인, 트윗화면 이동 모두!

**Comment by ahndohyun** [comment]
회원가입이 완료되면  트윗 화면으로 이동

**Comment by ahndohyun** [comment]
트윗페이지 반응형으로 // 메인페이지 css
