### ISSUE TITLE
file path를 줄여주세요.

### ISSUE THREAD

**Issue by Yeri-Kim** [ahndohyun/miniter_project#2]
Rotes.js에 중복 path를 줄여보세요.
index.js 를 활용하면 됩니다.

**Comment by ahndohyun** [comment]
모든 폴더 하위에 index.js 생성(path 에서 파일이 없으면 index를 호출한다)

**Comment by ahndohyun** [comment]
![스크린샷, 2019-06-30 20-42-45](https://user-images.githubusercontent.com/38515549/60396076-cfba0900-9b77-11e9-81be-a27e60f65daf.png)

**Comment by ahndohyun** [comment]
![스크린샷, 2019-06-30 20-42-57](https://user-images.githubusercontent.com/38515549/60396080-dd6f8e80-9b77-11e9-9ee4-d3c4b543367b.png)
